//////////////////////////////////////////////////
// File autogenerated by buildcounter
// Do not hand edit! (preferably)
//////////////////////////////////////////////////
#include "BuildID_HPL2_0.h"

static char gsBuildID[16] = "20251225011650";

const char* GetBuildID_HPL2_0()
{
    return gsBuildID;
}
